### ISSUE TITLE
Error Continuous Integration in GitHub Actions

### ISSUE THREAD

**Issue by abelthf** [testdrivenio/fastapi-tdd-docker#24]
**I have had errors when building the docker images in gitbub, for that reason I have cloned the project, the problem persisted**

thanks for your support

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[1006](https://github.com/abelthf/fastapii-tdd-docker/runs/7680389415?check_suite_focus=true#step:5:1007)
Removing intermediate container 95870fd272bd
[1007](https://github.com/abelthf/fastapii-tdd-docker/runs/7680389415?check_suite_focus=true#step:5:1008)
 ---> 530ee9ecdf51
[1008](https://github.com/abelthf/fastapii-tdd-docker/runs/7680389415?check_suite_focus=true#step:5:1009)
Step 11/13 : RUN flake8 .
[1009](https://github.com/abelthf/fastapii-tdd-docker/runs/7680389415?check_suite_focus=true#step:5:1010)
 ---> Running in fb605485132c
[1010](https://github.com/abelthf/fastapii-tdd-docker/runs/7680389415?check_suite_focus=true#step:5:1011)
Removing intermediate container fb605485132c
[1011](https://github.com/abelthf/fastapii-tdd-docker/runs/7680389415?check_suite_focus=true#step:5:1012)
 ---> aff27eef40ab
[1012](https://github.com/abelthf/fastapii-tdd-docker/runs/7680389415?check_suite_focus=true#step:5:1013)
Step 12/13 : RUN black --exclude=migrations .
[1013](https://github.com/abelthf/fastapii-tdd-docker/runs/7680389415?check_suite_focus=true#step:5:1014)
 ---> Running in aa374e6712d7
[1014](https://github.com/abelthf/fastapii-tdd-docker/runs/7680389415?check_suite_focus=true#step:5:1015)
Traceback (most recent call last):
[1015](https://github.com/abelthf/fastapii-tdd-docker/runs/7680389415?check_suite_focus=true#step:5:1016)
  File "/usr/local/bin/black", line 8, in <module>
[1016](https://github.com/abelthf/fastapii-tdd-docker/runs/7680389415?check_suite_focus=true#step:5:1017)
    sys.exit(patched_main())
[1017](https://github.com/abelthf/fastapii-tdd-docker/runs/7680389415?check_suite_focus=true#step:5:1018)
  File "/usr/local/lib/python3.10/site-packages/black/__init__.py", line 1372, in patched_main
[1018](https://github.com/abelthf/fastapii-tdd-docker/runs/7680389415?check_suite_focus=true#step:5:1019)
    patch_click()
[1019](https://github.com/abelthf/fastapii-tdd-docker/runs/7680389415?check_suite_focus=true#step:5:1020)
  File "/usr/local/lib/python3.10/site-packages/black/__init__.py", line 1358, in patch_click
[1020](https://github.com/abelthf/fastapii-tdd-docker/runs/7680389415?check_suite_focus=true#step:5:1021)
    from click import _unicodefun
[1021](https://github.com/abelthf/fastapii-tdd-docker/runs/7680389415?check_suite_focus=true#step:5:1022)
ImportError: cannot import name '_unicodefun' from 'click' (/usr/local/lib/python3.10/site-packages/click/__init__.py)
[1022](https://github.com/abelthf/fastapii-tdd-docker/runs/7680389415?check_suite_focus=true#step:5:1023)
The command '/bin/sh -c black --exclude=migrations .' returned a non-zero code: 1
[1023](https://github.com/abelthf/fastapii-tdd-docker/runs/7680389415?check_suite_focus=true#step:5:1024)

[1024](https://github.com/abelthf/fastapii-tdd-docker/runs/7680389415?check_suite_focus=true#step:5:1025)
**Error: Process completed with exit code 1.**

[https://github.com/abelthf/fastapii-tdd-docker/runs/7680389415?check_suite_focus=true](https://github.com/abelthf/fastapii-tdd-docker/runs/7680389415?check_suite_focus=true)

**Comment by dandersh** [comment]
Running into this problem as well (https://github.com/dandersh/fastapi-docker/actions/runs/3869384868) and was wondering what the solution was?

**Comment by dandersh** [comment]
Fixed it by manually adding my repo and granting it write access as outlined here: https://github.com/orgs/community/discussions/26274#discussioncomment-3251137
